package com.atguigu.mybatis.pojo;

public class Dept {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_dept.did
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    private Integer did;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_dept.dept_name
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_dept.did
     *
     * @return the value of d_dept.did
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_dept.did
     *
     * @param did the value for d_dept.did
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_dept.dept_name
     *
     * @return the value of d_dept.dept_name
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_dept.dept_name
     *
     * @param deptName the value for d_dept.dept_name
     *
     * @mbggenerated Fri Mar 04 21:24:50 GMT+08:00 2022
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }
}